/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{astro,md,mdx,ts,tsx}'],
  theme: {
    screens: {
      sm: '480px',
      md: '768px',
      lg: '1024px',
      xl: '1400px',
      '2xl': '1900px',
    },
    extend: {
      colors: {
        background: 'hsl(var(--background))',
        gradient: 'var(--gradient-main)',

        primary: {
          blue: {
            1: 'hsl(var(--primary-blue-1))',
            2: 'hsl(var(--primary-blue-2))',
            3: 'hsl(var(--primary-blue-3))',
            4: 'hsl(var(--primary-blue-4))',
            5: 'hsl(var(--primary-blue-5))',
            6: 'hsl(var(--primary-blue-6))',
            7: 'hsl(var(--primary-blue-7))',
            8: 'hsl(var(--primary-blue-8))',
            9: 'hsl(var(--primary-blue-9))',
            10: 'hsl(var(--primary-blue-10))',
          },
          green: {
            1: 'hsl(var(--primary-green-1))',
            2: 'hsl(var(--primary-green-2))',
            3: 'hsl(var(--primary-green-3))',
            4: 'hsl(var(--primary-green-4))',
            5: 'hsl(var(--primary-green-5))',
            6: 'hsl(var(--primary-green-6))',
            7: 'hsl(var(--primary-green-7))',
            8: 'hsl(var(--primary-green-8))',
            9: 'hsl(var(--primary-green-9))',
            10: 'hsl(var(--primary-green-10))',
          },
        },

        secondary: {
          'dark-green': {
            1: 'hsl(var(--secondary-dark-green-1))',
            2: 'hsl(var(--secondary-dark-green-2))',
            3: 'hsl(var(--secondary-dark-green-3))',
            4: 'hsl(var(--secondary-dark-green-4))',
            5: 'hsl(var(--secondary-dark-green-5))',
            6: 'hsl(var(--secondary-dark-green-6))',
            7: 'hsl(var(--secondary-dark-green-7))',
            8: 'hsl(var(--secondary-dark-green-8))',
            9: 'hsl(var(--secondary-dark-green-9))',
            10: 'hsl(var(--secondary-dark-green-10))',
          },
          'dark-purple': {
            1: 'hsl(var(--secondary-dark-purple-1))',
            2: 'hsl(var(--secondary-dark-purple-2))',
            3: 'hsl(var(--secondary-dark-purple-3))',
            4: 'hsl(var(--secondary-dark-purple-4))',
            5: 'hsl(var(--secondary-dark-purple-5))',
            6: 'hsl(var(--secondary-dark-purple-6))',
            7: 'hsl(var(--secondary-dark-purple-7))',
            8: 'hsl(var(--secondary-dark-purple-8))',
            9: 'hsl(var(--secondary-dark-purple-9))',
            10: 'hsl(var(--secondary-dark-purple-10))',
          },
          'dark-fiusha': {
            1: 'hsl(var(--secondary-dark-fiusha-1))',
            2: 'hsl(var(--secondary-dark-fiusha-2))',
            3: 'hsl(var(--secondary-dark-fiusha-3))',
            4: 'hsl(var(--secondary-dark-fiusha-4))',
            5: 'hsl(var(--secondary-dark-fiusha-5))',
            6: 'hsl(var(--secondary-dark-fiusha-6))',
            7: 'hsl(var(--secondary-dark-fiusha-7))',
            8: 'hsl(var(--secondary-dark-fiusha-8))',
            9: 'hsl(var(--secondary-dark-fiusha-9))',
            10: 'hsl(var(--secondary-dark-fiusha-10))',
          },
        },

        supporting: {
          error: {
            1: 'hsl(var(--supporting-error-1))',
            2: 'hsl(var(--supporting-error-2))',
            3: 'hsl(var(--supporting-error-3))',
            4: 'hsl(var(--supporting-error-4))',
            5: 'hsl(var(--supporting-error-5))',
            6: 'hsl(var(--supporting-error-6))',
            7: 'hsl(var(--supporting-error-7))',
            8: 'hsl(var(--supporting-error-8))',
            9: 'hsl(var(--supporting-error-9))',
            10: 'hsl(var(--supporting-error-10))',
          },
          success: {
            1: 'hsl(var(--supporting-success-1))',
            2: 'hsl(var(--supporting-success-2))',
            3: 'hsl(var(--supporting-success-3))',
            4: 'hsl(var(--supporting-success-4))',
            5: 'hsl(var(--supporting-success-5))',
            6: 'hsl(var(--supporting-success-6))',
            7: 'hsl(var(--supporting-success-7))',
            8: 'hsl(var(--supporting-success-8))',
            9: 'hsl(var(--supporting-success-9))',
            10: 'hsl(var(--supporting-success-10))',
          },
          warning: {
            1: 'hsl(var(--supporting-warning-1))',
            2: 'hsl(var(--supporting-warning-2))',
            3: 'hsl(var(--supporting-warning-3))',
            4: 'hsl(var(--supporting-warning-4))',
            5: 'hsl(var(--supporting-warning-5))',
            6: 'hsl(var(--supporting-warning-6))',
            7: 'hsl(var(--supporting-warning-7))',
            8: 'hsl(var(--supporting-warning-8))',
            9: 'hsl(var(--supporting-warning-9))',
            10: 'hsl(var(--supporting-warning-10))',
          },
          info: {
            1: 'hsl(var(--supporting-info-1))',
            2: 'hsl(var(--supporting-info-2))',
            3: 'hsl(var(--supporting-info-3))',
            4: 'hsl(var(--supporting-info-4))',
            5: 'hsl(var(--supporting-info-5))',
            6: 'hsl(var(--supporting-info-6))',
            7: 'hsl(var(--supporting-info-7))',
            8: 'hsl(var(--supporting-info-8))',
            9: 'hsl(var(--supporting-info-9))',
            10: 'hsl(var(--supporting-info-10))',
          },
        },

        neutral: {
          1: 'hsl(var(--neutral-1))',
          2: 'hsl(var(--neutral-2))',
          3: 'hsl(var(--neutral-3))',
          4: 'hsl(var(--neutral-4))',
          5: 'hsl(var(--neutral-5))',
          6: 'hsl(var(--neutral-6))',
          7: 'hsl(var(--neutral-7))',
          8: 'hsl(var(--neutral-8))',
          9: 'hsl(var(--neutral-9))',
          10: 'hsl(var(--neutral-10))',
          11: 'hsl(var(--neutral-11))',
          12: 'hsl(var(--neutral-12))',
          13: 'hsl(var(--neutral-13))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
