name: Publish Cloudlfare Production

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install

      - name: Build
        run: PLAUSIBLE_SITE_ID=${{ secrets.PLAUSIBLE_SITE_ID }} PLAUSIBLE_TOKEN=${{ secrets.PLAUSIBLE_TOKEN }} npm run build

      - name: Publish to Cloudlfare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          directory: dist
          branch: main
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

  version:
    runs-on: ubuntu-latest
    needs:
      - pages
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
