name: Publish Cloudlfare

on:
  push:
    branches:
      - develop

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Publish to Cloudlfare Pages
        uses: cloudflare/pages-action@v1
        with:
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            projectName: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
            directory: dist
            branch: develop
            gitHubToken: ${{ secrets.GITHUB_TOKEN }}